image: node:latest

stages:
  - Build
  - Test Connexion 
  - Test Micro
  - Test Cam
  - Test Micro et Cam
  - Test ajouter vignettes
  - Test configuration
  - Test ajouter question
  - Test evaluation 
  - Test quitter reunion
  - Test stopper reunion

cache:
  paths:
    - node_modules/

Build:
  stage: Build
  before_script:
    - apt-get update -q -y
    - apt-get --yes install xvfb
    - npm init -y
    - npm install nightwatch
  script:
    # Installing Google Chrome
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update -q -y
    - apt-get -y install google-chrome-stable 
    # Installing chromedriver
    - npm install chromedriver@110
    # installing all the packages
    #- npm install 
    # Ensuring everything is installed
    - ./node_modules/.bin/chromedriver --version
    - ./node_modules/.bin/nightwatch --version
    - /usr/bin/google-chrome --version
    # Install display manager
    - Xvfb -ac :99 -screen 0 1280x1024x16 &
    - export DISPLAY=:99


TS01-TC01-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC01-test-connexion.js
TS01-TC02-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC02-test-connexion.js
TS01-TC03-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC03-test-connexion.js 
TS01-TC04-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC04-test-connexion.js
TS01-TC05-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC05-test-connexion.js
TS01-TC06-test-connexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC06-test-connexion.js
TS01-TC07-test-reconnexion:
  stage: Test Connexion
  needs: [Build]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS01-TC07-test-reconnexion.js
TS02-TC01-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC01-test-micro.js 
TS02-TC02-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC02-test-micro.js 
TS02-TC03-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC03-test-micro-participants.js 
TS02-TC04-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC04-test-micro-participants.js 
TS02-TC05-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC05-test-micro-partage-ecran.js 
TS02-TC06-test-micro:
  stage: Test Micro
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS02-TC06-test-micro-cas-Quitte-reunion.js 
TS03-TC01-TC02-test-cam:
  stage: Test Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS03-TC01-TC02-test-cam.js 
TS03-TC03-test-cam:
  stage: Test Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS03-TC03-test-cam-participants.js 
TS03-TC04-test-cam:
  stage: Test Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS03-TC04-test-cam-participants.js 
TS03-TC05-test-cam:
  stage: Test Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS03-TC05-test-cam-partage-ecran.js 
TS03-TC06-test-cam:
  stage: Test Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS03-TC06-test-cam-cas-Quitte-reunion.js 
TS04-TC01-test-micro-cam:
  stage: Test Micro et Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS04-TC01-test-micro-et-cam.js 
TS04-TC02-test-micro-cam:
  stage: Test Micro et Cam
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS04-TC02-test-micro-et-cam.js 
TS06-TC01-ajouter-vignette:
  stage: Test ajouter vignettes
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS06-TC01-ajouter-vignette.js 
TS06-TC02-ajouter-vignette:
  stage: Test ajouter vignettes
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS06-TC02-ajouter-vignette.js 
TS08-test-configuration:
  stage: Test configuration
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS08-test-configuration.js 
TS011-TC01-test-ajouter-question:
  stage: Test ajouter question
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS011-TC01-test-ajouter-question.js 
TS015-test-evaluation:
  stage: Test evaluation
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS015-test-evaluation.js 
TS22-TC01-test-quitter-reunion:
  stage: Test quitter reunion
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS22-TC01-test-quitter-reunion.js 
TS22-TC02-test-quitter-reunion:
  stage: Test quitter reunion
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS22-TC02-test-quitter-reunion.js 
TS023-TC01-test-stopper-reunion:
  stage: Test stopper reunion
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS023-TC01-test-stopper-reunion.js 
TS023-TC02-test-arreter-reunion:
  stage: Test stopper reunion
  needs: [TS01-TC06-test-connexion]
  script:
    # Run nightwatch tests
    - npx nightwatch Tests/TS023-TC02-test-arreter-reunion.js 
